# See full lints list at:
# https://rust-lang.github.io/rust-clippy/master/index.html

doc-valid-idents = [
    "KiB", "MiB", "GiB", "TiB", "PiB", "EiB",
    "DirectX", "ECMAScript",
    "GPLv2", "GPLv3", "GitHub", "GitLab",
    "IPv4", "IPv6", "JavaScript", "NaN", "NaNs",
    "OAuth", "OpenGL", "OpenSSH", "OpenSSL", "OpenStreetMap", "TrueType",
    "iOS", "macOS", "TeX", "LaTeX", "BibTeX", "BibLaTeX", "MinGW",
    "BigInt64Array", "BigUint64Array",
    "ConstrainDOMString", "ConstrainULong",
    "DisplayMediaStreamConstraints",
    "DOMHighResTimeStamp",
    "getDisplayMedia", "getUserMedia", "gRPC",
    "MediaDevices", "MediaDeviceKind", "MediaDeviceInfo",
    "MediaStream", "MediaStreamConstraints",
    "MediaStreamTrack", "MediaStreamTrackState",
    "MediaTrackConstraints",
    "MessageEvent",
    "PulseAudio",
    "RTCAudioSenderStats",
    "RTCBundlePolicy",
    "RTCConfiguration",
    "RTCDataChannel",
    "RTCDtlsTransport",
    "RTCIceCandidate", "RTCIceCandidateInit", "RTCIceCandidateType",
    "RTCIceConnectionState",
    "RTCIceGatheringState",
    "RTCIceServer", "RTCIceTransport", "RTCIceTransportPolicy",
    "RTCPeerConnection", "RTCPeerConnectionIceEvent",
    "RTCRtcpParameters",
    "RTCRtpCodecParameters",
    "RTCRtpEncodingParameters",
    "RTCRtpHeaderExtensionParameters",
    "RTCRtpReceiver",
    "RTCRtpSender", "RTCSenderVideoTrackAttachmentStats",
    "RTCRtpTransceiver", "RTCRtpTransceiverDirection",
    "RTCSenderAudioTrackAttachmentStats",
    "RTCSessionDescription",
    "RTCSctpTransport",
    "RTCSdpType",
    "RTCSignalingState",
    "RTCStats", "RTCStatsReport",
    "RTCTrackEvent",
    "RTCVideoSenderStats",
    "VideoFacingModeEnum",
    "WebAPI", "WebDriver", "WebRTC", "WebSocket",
]
