name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android.
version: 0.1.7
author: cloudwebrtc <duanweiwei1982@gmail.com>
homepage: https://github.com/cloudwebrtc/flutter-webrtc

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      web:
        pluginClass: FlutterWebRTCPlugin
        fileName: lib/web/web_plugin.dart
    
environment:
  sdk: ">=2.2.2 <3.0.0"

