name: medea_flutter_webrtc
description: >
  Flutter WebRTC plugin for Android/iOS/macOS/Linux/Windows/Web, based on
  GoogleWebRTC, designed for and used in Medea Jason WebRTC client.
version: 0.12.0
homepage: https://github.com/instrumentisto/medea-flutter-webrtc

environment:
  flutter: ">=3.24.0"
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.7.0  # should be the same as in `Cargo.lock`
  freezed_annotation: ^2.4.4
  uuid: ^4.4.2
  web: ">=0.5.1 <2.0.0"
dev_dependencies:
  build_runner: ^2.4.12
  ffigen: ^11.0.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  import_sorter: ^4.6.0

flutter:
  plugin:
    platforms:
      android:
        package: com.instrumentisto.medea_flutter_webrtc
        pluginClass: MedeaFlutterWebrtcPlugin
      ios:
        pluginClass: MedeaFlutterWebrtcPlugin
      linux:
        pluginClass: MedeaFlutterWebrtcPlugin
      macos:
        pluginClass: MedeaFlutterWebrtcPlugin
      windows:
        pluginClass: MedeaFlutterWebrtcPluginCApi
