name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android.
version: 0.1.7
author: cloudwebrtc <duanweiwei1982@gmail.com>
homepage: https://github.com/cloudwebrtc/flutter-webrtc

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.cloudwebrtc.webrtc
    pluginClass: FlutterWebRTCPlugin

environment:
  sdk: ">=2.2.2 <3.0.0"

platforms:
  android:
    package: com.cloudwebrtc.webrtc
    pluginClass: FlutterWebRTCPlugin
  ios:
    pluginClass: FlutterWebRTCPlugin
  web:
    pluginClass: FlutterWebRTCPlugin
    fileName: lib/web_plugin.dart
