name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
version: 0.8.0-dev
homepage: https://github.com/cloudwebrtc/flutter-webrtc
environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 1.36.0  # should be the same as in `Cargo.lock`
  freezed_annotation: ^2.0.3
dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  import_sorter: ^4.6.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
