name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
version: 0.4.1
homepage: https://github.com/cloudwebrtc/flutter-webrtc
environment:
  sdk: '>=2.2.2 <3.0.0'
  flutter: ^1.10.0

dependencies:
  dart_webrtc: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  test:
    
flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
