name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
version: 0.10.8
homepage: https://github.com/cloudwebrtc/flutter-webrtc
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.22.0'

dependencies:
  collection: ^1.17.0
  dart_webrtc: ^1.4.6
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  web: ^0.5.1
  webrtc_interface: ^1.2.0
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.7
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^2.0.0
  pedantic: ^1.11.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin
