name: medea_flutter_webrtc
description: >
  Flutter WebRTC plugin for Android/iOS/macOS/Linux/Windows/Web, based on
  GoogleWebRTC, designed for and used in Medea Jason WebRTC client.
version: 0.8.0
homepage: https://github.com/instrumentisto/medea-flutter-webrtc

environment:
  flutter: ">=3.7.0"
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  ffi: ^2.0.1
  js: ^0.6.5
  flutter:
    sdk: flutter
  flutter_rust_bridge: 1.75.3  # should be the same as in `Cargo.lock`
  freezed_annotation: ^2.2.0
  meta: ^1.8.0
  uuid: ^3.0.7
dev_dependencies:
  build_runner: ^2.3.2
  ffigen: 7.2.8
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  import_sorter: ^4.6.0

flutter:
  plugin:
    platforms:
      android:
        package: com.instrumentisto.medea_flutter_webrtc
        pluginClass: MedeaFlutterWebrtcPlugin
      ios:
        pluginClass: MedeaFlutterWebrtcPlugin
      linux:
        pluginClass: MedeaFlutterWebrtcPlugin
      macos:
        pluginClass: MedeaFlutterWebrtcPlugin
      windows:
        pluginClass: MedeaFlutterWebrtcPluginCApi
