name: medea_flutter_webrtc
description: >
  Flutter WebRTC plugin for Android/iOS/macOS/Linux/Windows/Web, based on
  GoogleWebRTC, designed for and used in Medea Jason WebRTC client.
version: 0.10.0-dev
homepage: https://github.com/instrumentisto/medea-flutter-webrtc

environment:
  flutter: ">=3.10.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  ffi: ^2.0.1
  js: ^0.6.5
  flutter:
    sdk: flutter
  flutter_rust_bridge: 1.82.4  # should be the same as in `Cargo.lock`
  freezed_annotation: ^2.4.1
  meta: ^1.8.0
  uuid: ^4.2.1
dev_dependencies:
  build_runner: ^2.3.2
  ffigen: 8.0.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  import_sorter: ^4.6.0

dependency_overrides:
  # Pinned until `gql-dart` updates to 4 version:
  # https://github.com/gql-dart/gql/blob/master/links/gql_websocket_link/pubspec.yaml#L13
  uuid: ^3.0.7

flutter:
  plugin:
    platforms:
      android:
        package: com.instrumentisto.medea_flutter_webrtc
        pluginClass: MedeaFlutterWebrtcPlugin
      ios:
        pluginClass: MedeaFlutterWebrtcPlugin
      linux:
        pluginClass: MedeaFlutterWebrtcPlugin
      macos:
        pluginClass: MedeaFlutterWebrtcPlugin
      windows:
        pluginClass: MedeaFlutterWebrtcPluginCApi
