name: videosdk_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
version: 0.0.3
homepage: https://www.videosdk.live
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.22.0"

dependencies:
  collection: 1.18.0
  dart_webrtc: ^1.4.9
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  web: ^1.1.0
  webrtc_interface: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^5.0.0
  pedantic: ^1.11.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: live.videosdk.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin
