[package]
name = "flutter-webrtc-native"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
cxx = "1.0"
derive_more = "0.99"
libwebrtc-sys = { path = "../libwebrtc-sys" }

[build-dependencies]
anyhow = "1.0"
cxx-build = "1.0"
walkdir = "2.3"
